### PR TITLE
Bridge speedup

### PR DESCRIPTION
**Pull request by jordanpwood**
Here are the changes for speeding up the bridge.

### CODE REVIEW

**Comment by jordanpwood** [comment]
@karlbecker, we don't want to merge and delete this branch, since the podfile refers specifically to this branch.

**Comment by karlbecker** [comment]
We could perhaps refer to a tag in this repo, but we can also just merge in a new change that refers to develop in this repo once we merge this in.  Good point though @jordanpwood !

**Comment by jordanpwood** [comment]
Hopefully, we will just move back to the marcuswestin branch.

**Comment by karlbecker** [comment]
After these comments are addressed, @jordanpwood , I think we're good to merge here!  Just don't delete the branch  ;)

**Comment by jordanpwood** [comment]
I can't remember where I left this, and it appears that we won't ever be using this, so I'm just going to close this.

**Pull request closed without merging**
